import type { SidebarItem } from "@astrojs/starlight/types";

export const sidebar: SidebarItem[] = [
  {
    label: 'Getting Started',
    items: [
      { label: 'Installation', slug: 'getting-started/installation' },
      { label: 'Quick Start', slug: 'getting-started/quick-start' },
      { label: 'Core Concepts', slug: 'getting-started/core-concepts' },
    ],
  },
  {
    label: 'Using Syllago',
    items: [
      { label: 'The TUI', slug: 'using-syllago/tui' },
      {
        label: 'CLI Reference',
        collapsed: true,
        items: [
          { label: 'add', slug: 'using-syllago/cli-reference/add' },
          { label: 'compat', slug: 'using-syllago/cli-reference/compat' },
          {
            label: 'completion',
            collapsed: true,
            items: [
              { label: 'completion', slug: 'using-syllago/cli-reference/completion' },
              { label: 'bash', slug: 'using-syllago/cli-reference/completion-bash' },
              { label: 'fish', slug: 'using-syllago/cli-reference/completion-fish' },
              { label: 'powershell', slug: 'using-syllago/cli-reference/completion-powershell' },
              { label: 'zsh', slug: 'using-syllago/cli-reference/completion-zsh' },
            ],
          },
          {
            label: 'config',
            collapsed: true,
            items: [
              { label: 'config', slug: 'using-syllago/cli-reference/config' },
              { label: 'add', slug: 'using-syllago/cli-reference/config-add' },
              { label: 'list', slug: 'using-syllago/cli-reference/config-list' },
              { label: 'paths', slug: 'using-syllago/cli-reference/config-paths' },
              { label: 'paths clear', slug: 'using-syllago/cli-reference/config-paths-clear' },
              { label: 'paths set', slug: 'using-syllago/cli-reference/config-paths-set' },
              { label: 'paths show', slug: 'using-syllago/cli-reference/config-paths-show' },
              { label: 'remove', slug: 'using-syllago/cli-reference/config-remove' },
            ],
          },
          { label: 'convert', slug: 'using-syllago/cli-reference/convert' },
          { label: 'create', slug: 'using-syllago/cli-reference/create' },
          { label: 'explain', slug: 'using-syllago/cli-reference/explain' },
          {
            label: 'info',
            collapsed: true,
            items: [
              { label: 'info', slug: 'using-syllago/cli-reference/info' },
              { label: 'formats', slug: 'using-syllago/cli-reference/info-formats' },
              { label: 'providers', slug: 'using-syllago/cli-reference/info-providers' },
            ],
          },
          { label: 'init', slug: 'using-syllago/cli-reference/init' },
          { label: 'inspect', slug: 'using-syllago/cli-reference/inspect' },
          { label: 'install', slug: 'using-syllago/cli-reference/install' },
          { label: 'list', slug: 'using-syllago/cli-reference/list' },
          {
            label: 'loadout',
            collapsed: true,
            items: [
              { label: 'loadout', slug: 'using-syllago/cli-reference/loadout' },
              { label: 'apply', slug: 'using-syllago/cli-reference/loadout-apply' },
              { label: 'create', slug: 'using-syllago/cli-reference/loadout-create' },
              { label: 'list', slug: 'using-syllago/cli-reference/loadout-list' },
              { label: 'remove', slug: 'using-syllago/cli-reference/loadout-remove' },
              { label: 'status', slug: 'using-syllago/cli-reference/loadout-status' },
            ],
          },
          { label: 'publish', slug: 'using-syllago/cli-reference/publish' },
          {
            label: 'registry',
            collapsed: true,
            items: [
              { label: 'registry', slug: 'using-syllago/cli-reference/registry' },
              { label: 'add', slug: 'using-syllago/cli-reference/registry-add' },
              { label: 'create', slug: 'using-syllago/cli-reference/registry-create' },
              { label: 'items', slug: 'using-syllago/cli-reference/registry-items' },
              { label: 'list', slug: 'using-syllago/cli-reference/registry-list' },
              { label: 'remove', slug: 'using-syllago/cli-reference/registry-remove' },
              { label: 'sync', slug: 'using-syllago/cli-reference/registry-sync' },
            ],
          },
          { label: 'remove', slug: 'using-syllago/cli-reference/remove' },
          {
            label: 'sandbox',
            collapsed: true,
            items: [
              { label: 'sandbox', slug: 'using-syllago/cli-reference/sandbox' },
              { label: 'allow-domain', slug: 'using-syllago/cli-reference/sandbox-allow-domain' },
              { label: 'allow-env', slug: 'using-syllago/cli-reference/sandbox-allow-env' },
              { label: 'allow-port', slug: 'using-syllago/cli-reference/sandbox-allow-port' },
              { label: 'check', slug: 'using-syllago/cli-reference/sandbox-check' },
              { label: 'deny-domain', slug: 'using-syllago/cli-reference/sandbox-deny-domain' },
              { label: 'deny-env', slug: 'using-syllago/cli-reference/sandbox-deny-env' },
              { label: 'deny-port', slug: 'using-syllago/cli-reference/sandbox-deny-port' },
              { label: 'domains', slug: 'using-syllago/cli-reference/sandbox-domains' },
              { label: 'env', slug: 'using-syllago/cli-reference/sandbox-env' },
              { label: 'info', slug: 'using-syllago/cli-reference/sandbox-info' },
              { label: 'ports', slug: 'using-syllago/cli-reference/sandbox-ports' },
              { label: 'run', slug: 'using-syllago/cli-reference/sandbox-run' },
            ],
          },
          { label: 'share', slug: 'using-syllago/cli-reference/share' },
          { label: 'sync-and-export', slug: 'using-syllago/cli-reference/sync-and-export' },
          { label: 'uninstall', slug: 'using-syllago/cli-reference/uninstall' },
          { label: 'update', slug: 'using-syllago/cli-reference/update' },
          { label: 'version', slug: 'using-syllago/cli-reference/version' },
        ],
      },
      {
        label: 'Content Types',
        collapsed: true,
        items: [
          { label: 'Overview', slug: 'using-syllago/content-types' },
          { label: 'Rules', slug: 'using-syllago/content-types/rules' },
          { label: 'Skills', slug: 'using-syllago/content-types/skills' },
          { label: 'Agents', slug: 'using-syllago/content-types/agents' },
          { label: 'MCP Configs', slug: 'using-syllago/content-types/mcp-configs' },
          { label: 'Hooks', slug: 'using-syllago/content-types/hooks' },
          { label: 'Commands', slug: 'using-syllago/content-types/commands' },
        ],
      },
      {
        label: 'Collections',
        collapsed: true,
        items: [
          { label: 'Overview', slug: 'using-syllago/collections' },
          { label: 'Library', slug: 'using-syllago/collections/library' },
          { label: 'Registries', slug: 'using-syllago/collections/registries' },
          { label: 'Loadouts', slug: 'using-syllago/collections/loadouts' },
        ],
      },
      {
        label: 'Supported Providers',
        collapsed: true,
        items: [
          { label: 'Overview', slug: 'using-syllago/providers' },
          { label: 'Claude Code', slug: 'using-syllago/providers/claude-code' },
          { label: 'Cursor', slug: 'using-syllago/providers/cursor' },
          { label: 'Windsurf', slug: 'using-syllago/providers/windsurf' },
          { label: 'Copilot', slug: 'using-syllago/providers/copilot' },
          { label: 'Cline', slug: 'using-syllago/providers/cline' },
          { label: 'Roo Code', slug: 'using-syllago/providers/roo-code' },
          { label: 'Kiro', slug: 'using-syllago/providers/kiro' },
          { label: 'Zed', slug: 'using-syllago/providers/zed' },
          { label: 'Gemini CLI', slug: 'using-syllago/providers/gemini-cli' },
          { label: 'OpenCode', slug: 'using-syllago/providers/opencode' },
          { label: 'Codex', slug: 'using-syllago/providers/codex' },
        ],
      },
      { label: '.syllago.yaml Format', slug: 'using-syllago/syllago-yaml' },
      { label: 'Format Conversion', slug: 'using-syllago/format-conversion' },
    ],
  },
  {
    label: 'Advanced',
    collapsed: true,
    items: [
      { label: 'Sandbox', slug: 'advanced/sandbox' },
      { label: 'Team Setup', slug: 'advanced/team-setup' },
      { label: 'Troubleshooting', slug: 'advanced/troubleshooting' },
    ],
  },
  {
    label: 'Error Codes',
    collapsed: true,
    autogenerate: { directory: 'errors' },
  },
  {
    label: 'For AI assistants',
    slug: 'for-ai-assistants',
  },
];
